### PR TITLE
feat: add RBAC permissions for leases

### PR DESCRIPTION
**Pull request by akshatagarwl**
This is a non-breaking change.

### CODE REVIEW

**Comment by akshatagarwl** [comment]
I have already tested this in my local Kubernetes cluster but would love to have another set of eyes + machine on it @boratanrikulu

**Comment by mcoklica1** [comment]
Hey @akshatagarwl I can point our argocd to look for "push-zzrwuzzrtzps" as a targetRevision (the branch from this repo)... this way (re)deployed STA will have clusterroles with your changes inside `charts/sematext-agent/templates/clusterrole.yaml`.

WDYT?

**Comment by boratanrikulu** [comment]
I will merge and release this one within today

**Review by boratanrikulu — APPROVED** [review]
LGTM

**Pull request merged**
