### PR TITLE
allow 60 seconds for agent startup

### PR DESCRIPTION
**Pull request by lujomon**

### CODE REVIEW

**Comment by rabbitstack** [comment]
@lujomon you forgot to add reviewers to this PR.

**Comment by lujomon** [comment]
UI doesn't allow me.

**Comment by rabbitstack** [comment]
ping Ciprian so he is aware of this PR.

**Comment by hakman** [comment]
Would it make sense to remove the readiness probe?

**Comment by lujomon** [comment]
I'm not sure what was the purpose of readiness probe? Seems like condition is the same as for liveness probe, so not sure if it would ever kick in?

**Comment by hakman** [comment]
Exactly. Also, not sure if there's a case when we want to wait for agent to recover and not just kill it.

**Comment by lujomon** [comment]
Removed. I don't think there's such case, but let's wait for @rabbitstack to confirm.

**Pull request merged**
